# Generated by Django 4.1.1 on 2022-09-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('trabajo', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
